import math
a = int(input())
b = int(input())
print('The sum of a and b is', a + b)
print('The difference when b is subtracted from a is', a - b)
print('The product of a and b is', a * b)
print('The quotient when a is divided by b is', a / b)
print('The remainder when a is divided by b is', a // b)
print('The result of log10 a is', math.log(a))
print('The result of a^b is', a ^ b)
